# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('stock', models.IntegerField()),
                ('shop_location', models.TextField()),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
